services:
  dungeon-service:
    image: node:alpine
    volumes:
      - ./dungeon-service:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  fight-service:
    image: node:alpine
    volumes:
      - ./fight-service:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3000"

  player-service:
    image: node:alpine
    volumes:
      - ./player-service:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3002:3000"
    environment:
      - MONGO_URL=mongodb://player-db:27017/player
    depends_on:
      - player-db

  player-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - player-db-data:/data/db

  game-service:
    image: node:alpine
    volumes:
      - ./game-service:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3003:3000"
    depends_on:
      - dungeon-service
      - fight-service
      - player-service

  front-service:
    image: node:alpine
    volumes:
      - ./front-service:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3004:3000"

volumes:
  player-db-data: